using Toybox.Graphics;
module cfg {
    const bufferWidth = 260;
    const bufferHeight = 260;
    const analogClockX = 130.0;
    const analogClockY = 130.0;
    const initClip = [[1.0, 141.0], [1.0, 0.0], [18.0, 0.0], [18.0, 141.0]];

    // Text parameters migrated from resources/layouts/layout.xml.
    const currentHourX = 112;
    const currentHourY = 153;
    const currentHourColor = 0xFFFFFF;
    const currentHourJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const currentHourVisible = true;
    const currentHourInitialText = "10:10";
    const currentMinuteX = 148;
    const currentMinuteY = 153;
    const currentMinuteColor = 0xFFAA00;
    const currentMinuteJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const currentMinuteVisible = true;
    const currentMinuteInitialText = "10:10";
    const weekDayX = 73;
    const weekDayY = 186;
    const weekDayColor = 0xFF0055;
    const weekDayJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const weekDayVisible = true;
    const weekDayInitialText = "MON";
    const dateX = 73;
    const dateY = 196;
    const dateColor = 0x000000;
    const dateJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const dateVisible = true;
    const dateInitialText = "25";
    const monthX = 73;
    const monthY = 213;
    const monthColor = 0x000000;
    const monthJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const monthVisible = true;
    const monthInitialText = "JAN";
    const stepsCountX = 102;
    const stepsCountY = 116;
    const stepsCountColor = 0x000000;
    const stepsCountJustification = Graphics.TEXT_JUSTIFY_RIGHT;
    const stepsCountVisible = true;
    const stepsCountInitialText = "12340";
    const stepsLabelX = 82;
    const stepsLabelY = 130;
    const stepsLabelColor = 0x555555;
    const stepsLabelJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const stepsLabelVisible = true;
    const stepsLabelInitialText = "steps";
    const heartRateX = 188;
    const heartRateY = 71;
    const heartRateColor = 0x000000;
    const heartRateJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const heartRateVisible = true;
    const heartRateInitialText = "75";
    const energyLevelX = 140;
    const energyLevelY = 203;
    const energyLevelColor = 0x000000;
    const energyLevelJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const energyLevelVisible = false;
    const energyLevelInitialText = "80%";
    const barometerX = 73;
    const barometerY = 72;
    const barometerColor = 0x000000;
    const barometerJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const barometerVisible = true;
    const barometerInitialText = "1013";
    const batteryX = 188;
    const batteryY = 119;
    const batteryColor = 0x000000;
    const batteryJustification = Graphics.TEXT_JUSTIFY_LEFT;
    const batteryVisible = true;
    const batteryInitialText = "80%";
    const solarChargingX = 82;
    const solarChargingY = 152;
    const solarChargingColor = 0x000055;
    const solarChargingJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const solarChargingVisible = true;
    const solarChargingInitialText = "5";
    const bluetoothX = 82;
    const bluetoothY = 166;
    const bluetoothColor = 0x000055;
    const bluetoothJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const bluetoothVisible = true;
    const bluetoothInitialText = "5";
    const alarmX = 178;
    const alarmY = 152;
    const alarmColor = 0x000055;
    const alarmJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const alarmVisible = true;
    const alarmInitialText = "0";
    const vibrateX = 178;
    const vibrateY = 166;
    const vibrateColor = 0x000055;
    const vibrateJustification = Graphics.TEXT_JUSTIFY_CENTER;
    const vibrateVisible = true;
    const vibrateInitialText = "8";

    // Weather drawable parameters migrated from layout.xml.
    const weatherX = 108;
    const weatherY = 48;
    const weatherWidth = 40;
    const weatherColor = 0x005555;

    // Seconds hand parameters and bitmap geometry.
    const secondsX = 130;
    const secondsY = 130;
    const secondsHandResource = Rez.Drawables.SecondsHand;
    const secondsBufferWidth = 7;
    const secondsBufferHeight = 141;
    const secondsHandDx = -3.5;
    const secondsHandDy = -110.0;
    const secondsClip = [[1.0, 141.0], [1.0, 0.0], [7.0, 0.0], [7.0, 141.0]];

    // Analog clock resource parameters and bitmap pivot offsets.
    // analogClockX/Y above retain the layout's original center (130, 130).
    const hourHandResource = Rez.Drawables.HourHand;
    const minuteHandResource = Rez.Drawables.MinuteHand;
    const hourHandDx = -10.0;
    const hourHandDy = -59.0;
    const minuteHandDx = -5.5;
    const minuteHandDy = -112.5;
}
